### ISSUE TITLE
autogenerated code can't commit

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/create-lwc-app#267]
### Summary

missing some dev dependencies.  Solved by adding

"@typescript-eslint/eslint-plugin": "^2.4.0",
 "@typescript-eslint/parser": "^2.4.0",

### Steps To Reproduce:

1.  use generator script with yarn, ts
2. try to commit the generated code

### Expected result
commit

### Actual result
eslint failure from pre-commit hook

### Additional information
eslint [failed]
→ 
Running tasks for ./src/**/*.ts [failed]
→ 
prettier --write [completed]
Running tasks for **/*.{css,html,js,json,md,ts,yaml,yml} [completed]
Running tasks... [failed]

✖ eslint found some errors. Please fix them and try committing again.

Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json': Cannot find module '@typescript-eslint/parser'
Require stack:
- /Users/shane.mclaughlin/code/campground/df19/electron-super-heroku/.eslintrc.json
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
  at Function.resolve (internal/modules/cjs/helpers.js:33:19)
  at Object.resolve (/Users/shane.mclaughlin/code/campground/df19/electron-super-heroku/node_modules/eslint/lib/shared/relative-module-resolver.js:44:50)
  at ConfigArrayFactory._loadParser (/Users/shane.mclaughlin/code/campground/df19/electron-super-heroku/node_modules/eslint/lib/cli-engine/config-array-factory.js:756:45)
  at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/shane.mclaughlin/code/campground/df19/electron-super-heroku/node_modules/eslint/lib/cli-engine/config-array-factory.js:552:32)
  at _normalizeObjectConfigDataBody.next (<anonymous>)
  at ConfigArrayFactory._normalizeObjectConfigData (/Users/shane.mclaughlin/code/campground/df19/electron-super-heroku/node_modules/eslint/lib/cli-engine/config-array-factory.js:491:20)
  at _normalizeObjectConfigData.next (<anonymous>)
  at createConfigArray (/Users/shane.mclaughlin/code/campground/df19/electron-super-heroku/node_modules/eslint/lib/cli-engine/config-array-factory.js:307:25)
  at ConfigArrayFactory.loadInDirectory (/Users/shane.mclaughlin/code/campground/df19/electron-super-heroku/node_modules/eslint/lib/cli-engine/config-array-factory.js:400:16)
husky > pre-commit hook failed (add --no-verify to bypass)
> git config --get-all user.name
> git config --get-all user.email
> git show :package.json
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :package.json

**Comment by muenzpraeger** [comment]
Already fixed [in 1.3.5](https://github.com/muenzpraeger/create-lwc-app/pull/250). You can try the beta channel for that. ;-)

It will be shipped tomorrow (there’s a dependency on Trailhead content in that release).
