### ISSUE TITLE
Cannot find module '../lib'

### ISSUE THREAD

**Issue by DeadlySemiColon** [muenzpraeger/create-lwc-app#531]
### Summary

Attempting to install a boilerplate lwc app.

### Steps To Reproduce:

create-lwc-app [app name] or npx create-lwc-app [app-name]

### Expected result

Generate boilerplate lwc app

### Actual result

$ create-lwc-app test
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '../lib'
Require stack:
- C:\Users\User\AppData\Roaming\npm\node_modules\create-lwc-app\bin\run
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\create-lwc-app\bin\run:12:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\create-lwc-app\\bin\\run'
  ]
}

_Feel free to attach a screenshot or code snippets_.

**Comment by muenzpraeger** [comment]
Thanks for raising, published a fix

**Comment by DeadlySemiColon** [comment]
Awesome! Thanks for the quick response.
