### ISSUE TITLE
NoLwcModuleFound [Error]: Unable to resolve "xxx" from "yyy"

### ISSUE THREAD

**Issue by JeroenSfdc** [muenzpraeger/create-lwc-app#589]
### Summary

When building my app modules which are other directories are not resolved.

```
src
  |--> client
             |--> modules
                           |--> data
                                     |--> authService.js
                           |--> my
                                    |--> app
                                              |--> app.js
```

`authService.js`

```
const URL = '/oauth2/auth';

export const getLogin = () => fetch(URL)
  .then(response => {
    if (!response.ok) {
      throw new Error('No response from server');
    }
    return response.json();
  })
  .then(result => {
    //contacts = result.data;
    return result;
  });
```

`app.js`

imports from `'data/authService'`. 
Only when I'd import from `'../../authServices'` the build succeeds. 

```
import { LightningElement, track } from 'lwc';
import { getLoggedInUser } from 'data/authService';

export default class App extends LightningElement {
    @track loggedUser = undefined;
    @track state;

    connectedCallback() {
        getLoggedInUser().then((response) => {
            if (response.user_id === undefined) {
                this.loggedUser = undefined;
                this.state = 'login';
            } else {
                this.loggedUser = response;
                this.state = 'list';
            }
        });
    }

    get isLoginView() {
        return this.state === 'login';
    }
}
```

`npm run build:development`

```

/Users/jburgers/VscProjects/sf-performance-app/node_modules/@lwc/module-resolver/dist/commonjs/index.js:134
    throw new errors_1.NoLwcModuleFound(importee, dirname);
    ^

NoLwcModuleFound [Error]: Unable to resolve "data/authService" from "/Users/jburgers/VscProjects/sf-performance-app"
    at Object.resolveModule (/Users/jburgers/VscProjects/sf-performance-app/node_modules/@lwc/module-resolver/dist/commonjs/index.js:134:11)
    at Array.<anonymous> (/Users/jburgers/VscProjects/sf-performance-app/node_modules/lwc-services/lib/utils/webpack/module-resolver.js:59:41)
    at Storage.finished (/Users/jburgers/VscProjects/sf-performance-app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/jburgers/VscProjects/sf-performance-app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at callback (/Users/jburgers/VscProjects/sf-performance-app/node_modules/graceful-fs/polyfills.js:295:20)
```

### Steps To Reproduce:

1. `npx create-lwc-app lwc-test-app`

```
? Do you want to use the simple setup? Yes
? Package name for npm lwc-test-app2
? Select the type of app you want to create Standard web app
? Do you want a basic Express API server? Yes
```

2. create `data\authService.js
3. update `app.js`

### Expected result

Succesful build. Modules should be resolved using the `lwc-services.config.js` `moduleDir`

` moduleDir: './src/client/modules',`

### Actual result

Build fails.

**Comment by muenzpraeger** [comment]
The folder structure is `namespace/component/components.js`, so the correct folder structure for your data needs to be `src/client/modules/data/authService/authService.js`.

**Comment by JeroenSfdc** [comment]
Thanks @muenzpraeger. That's it indeed.
