### ISSUE TITLE
missing devDependencies in package.json

### ISSUE THREAD

**Issue by jpdevspace** [muenzpraeger/create-lwc-app#858]
### Summary

When I try to run the app with `npm run watch` it complains about commands not being found. The exact things it complains about depends on whether I decide to include the Express server or not during the installation wizard. If I choose NOT to include Express the error message is `lwc-services: command not found`. If I include it, then it complains about `run-p`. After a little digging, I believe the problem is that after the installation wizard my `package.json` doesn't have some fields like a `devDependecies` section, so I think it's missing some dependencies it needs to install.

I've tried:
- running `npm install` after the installation wizard
- removing `node_modules` and running `npm install`
- removing `node_modules`, `npm cache clean --force` and running `npm install`
- starting from scratch on a brand new folder
- using different versions of Node (v14.16.0 and v16.1.0)

### Steps To Reproduce:

1.  Run `npx create-lwc-app my-new-app`
1.  Go through the wizard with the easy (and defaults) installation and no Express API server
1.  Run `cd my-new-app`
1.  Run `npx run watch`

### Expected result

The app should build and the local development server should start.

### Actual result

I get an error `lwc-services: command not found`

### Additional information

I'm running:
macOS (Big Sur)
I tried using Node v14.16.0 and Node v16.1.0 (I'm using nvm)
npm v7.11.2

Here's my `package.json` file immediately after running through the installation wizard
```
{
    "name": "my-new-app",
    "description": "My amazing LWC app",
    "version": "0.0.1",
    "author": "my name",
    "bugs": "https://github.com/my-name/my-new-app/issues",
    "dependencies": {
        "compression": "^1.7.4",
        "express": "^4.17.1",
        "helmet": "^4.6.0"
    },
    "engines": {
        "node": ">=10.13.0",
        "npm": ">=6.4.1",
        "yarn": ">=1.9.4"
    },
    "homepage": "https://github.com/my-name/my-new-app",
    "husky": {
        "hooks": {
            "pre-commit": "lint-staged"
        }
    },
    "keywords": [
        "lwc"
    ],
    "license": "MIT",
    "lint-staged": {
        "**/*.{css,html,js,json,md,ts,yaml,yml}": [
            "prettier --write"
        ],
        "./src/**/*.js": [
            "eslint"
        ]
    },
    "repository": "my-name/my-new-app",
    "scripts": {
        "build": "lwc-services build -m production",
        "build:development": "lwc-services build",
        "lint": "eslint ./src/**/*.js",
        "prettier": "prettier --write \"**/*.{css,html,js,json,md,ts,yaml,yml}\"",
        "prettier:verify": "prettier --list-different \"**/*.{css,html,js,json,md,ts,yaml,yml}\"",
        "serve": "node scripts/server.js",
        "test:unit": "lwc-services test:unit",
        "test:unit:coverage": "lwc-services test:unit --coverage",
        "test:unit:debug": "lwc-services test:unit --debug",
        "test:unit:watch": "lwc-services test:unit --watch",
        "watch": "lwc-services watch"
    }
}

```

after the installation wizard I get the following on my terminal
```
create package.json
   create .eslintrc.json
   create .eslintignore
   create .prettierignore
   create .prettierrc
   create .gitignore
   create src/modules/jsconfig.json
   create lwc.config.json
   create lwc-services.config.js
   create jest.config.js
   create README.md
   create src/index.html
   create src/index.js
   create src/modules/my/app/app.css
   create src/modules/my/app/app.js
   create src/modules/my/app/app.html
   create src/modules/my/greeting/greeting.css
   create src/modules/my/greeting/greeting.js
   create src/modules/my/greeting/greeting.html
   create src/modules/my/app/__tests__/app.test.js
   create src/modules/my/greeting/__tests__/greeting.test.js
   create src/resources/lwc.png
   create src/resources/favicon.ico
   create scripts/server.js

added 56 packages, and audited 57 packages in 898ms

found 0 vulnerabilities
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: webpack@5.28.0
npm WARN node_modules/webpack
npm WARN   webpack@"^5.21.1" from lwc-services@3.0.4
npm WARN   node_modules/lwc-services
npm WARN     dev lwc-services@"^3.0.4" from the root project
npm WARN   2 more (babel-loader, copy-webpack-plugin)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer webpack@"^4.0.0" from error-overlay-webpack-plugin@0.4.2
npm WARN node_modules/error-overlay-webpack-plugin
npm WARN   error-overlay-webpack-plugin@"0.4.2" from lwc-services@3.0.4
npm WARN   node_modules/lwc-services
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-compilation-targets@^7.13.16.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/my-user/.npm/_logs/log-file-debug.log
```

The complete log is almost 6000 lines but here is the last few lines
```
5917 timing command:install Completed in 4670ms
5918 verbose type range
5919 verbose stack @babel/helper-compilation-targets: No matching version found for @babel/helper-compilation-targets@^7.13.16.
5919 verbose stack     at module.exports (/Users/my-user/.nvm/versions/node/v16.1.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
5919 verbose stack     at /Users/my-user/.nvm/versions/node/v16.1.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
5919 verbose stack     at async Promise.all (index 2)
5919 verbose stack     at async Arborist.[buildDepStep] (/Users/my-user/.nvm/versions/node/v16.1.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:924:5)
5919 verbose stack     at async Arborist.buildIdealTree (/Users/my-user/.nvm/versions/node/v16.1.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
5919 verbose stack     at async Promise.all (index 1)
5919 verbose stack     at async Arborist.reify (/Users/my-user/.nvm/versions/node/v16.1.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:135:5)
5919 verbose stack     at async Install.install (/Users/my-user/.nvm/versions/node/v16.1.0/lib/node_modules/npm/lib/install.js:137:5)
5920 verbose cwd /Users/my-user/DEV/LWC/my-new-app
5921 verbose Darwin 20.4.0
5922 verbose argv "/Users/my-user/.nvm/versions/node/v16.1.0/bin/node" "/Users/my-user/.nvm/versions/node/v16.1.0/bin/npm" "install" "husky" "lint-staged" "prettier" "eslint" "lwc-services@^3.0.4" "--save-dev" "--no-ignore-scripts" "--cache-min" "86400"
5923 verbose node v16.1.0
5924 verbose npm  v7.11.2
5925 error code ETARGET
5926 error notarget No matching version found for @babel/helper-compilation-targets@^7.13.16.
5927 error notarget In most cases you or one of your dependencies are requesting
5927 error notarget a package version that doesn't exist.
5928 verbose exit 1
```

**Comment by jpdevspace** [comment]
I got the local dev server up and running. I just manually installed `lwc-services` with `npm i lwc-services` I still think my `package.json` file is missing some packages.
