### ISSUE TITLE
How do I run a single unit test?

### ISSUE THREAD

**Issue by gamedevsam** [muenzpraeger/create-lwc-app#901]
**What is missing from the application? Please describe.**
A way to run only one unit test, aka pass parameters to Jest runner.

**Describe the solution you'd like**
Be able to run a single Jest test, either via the command line or through VS code's Jest Runner extension.

More info on Jest command line: https://stackoverflow.com/a/55279902/706442

**Describe alternatives you've considered**
There is no alternative.

**Additional context**
Currently doing test driven development with lwc-services is quite painful due to the need to run every unit test every time.

**Comment by muenzpraeger** [comment]
There are two options.

First, you call Jest directly, for example `yarn jest -i path/to/your/test.js`. Or second, you use the `-p` parameter of `lwc-services test:unit` to passthrough arguments to Jest.

**Comment by gamedevsam** [comment]
Using `-p` to forward parameters to jest works as expected, ty!

When I try to run jest directly I get this error:

```
    TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

      at Object.getCacheKey (node_modules/@lwc/jest-transformer/src/index.js:116:14)
      at ScriptTransformer._getCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:280:41)
      at ScriptTransformer._getFileCachePath (node_modules/@jest/transform/build/ScriptTransformer.js:351:27)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:588:32)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:758:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:815:19)
```

Any clue what this means?
