### ISSUE TITLE
Not able to start a local server 

### ISSUE THREAD

**Issue by fddemora** [muenzpraeger/create-lwc-app#925]
not sure what the issue could be here. 
i'm running `npm run watch` and this happens 
Same issue running `npm run watch:client`

```
⚡⚡⚡⚡⚡  Lightning Web Components ⚡⚡⚡⚡⚡


📦  Starting build process.
🌎  Local server listening: http://localhost:3001
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (C:\Users\Demor\app\node_modules\lwc-services\node_modules\webpack\lib\util\createHash.js:145:18)
    at BulkUpdateDecorator.update (C:\Users\Demor\app\node_modules\lwc-services\node_modules\webpack\lib\util\createHash.js:46:50)
    at OriginalSource.updateHash (C:\Users\Demor\app\node_modules\lwc-services\node_modules\webpack-sources\lib\OriginalSource.js:104:8)
    at NormalModule._initBuildHash (C:\Users\Demor\app\node_modules\lwc-services\node_modules\webpack\lib\NormalModule.js:870:17)
    at handleParseResult (C:\Users\Demor\app\node_modules\lwc-services\node_modules\webpack\lib\NormalModule.js:936:10)
    at C:\Users\Demor\app\node_modules\lwc-services\node_modules\webpack\lib\NormalModule.js:1028:4
    at processResult (C:\Users\Demor\app\node_modules\lwc-services\node_modules\webpack\lib\NormalModule.js:745:11)
    at C:\Users\Demor\app\node_modules\lwc-services\node_modules\webpack\lib\NormalModule.js:809:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.3.0
ERROR: "watch:client" exited with 1.
```

Here is my json package folder
```
{
    "name": "app",
    "version": "0.0.1",
    "author": "Fellipe Demoraes",
    "bugs": "https://github.com/Fellipe Demoraes/app/issues",
    "dependencies": {
        "compression": "^1.7.4",
        "express": "^4.17.2",
        "helmet": "^5.0.1"
    },
    "engines": {
        "node": ">=10.13.0",
        "npm": ">=6.4.1",
        "yarn": ">=1.9.4"
    },
    "homepage": "https://github.com/Fellipe Demoraes/app",
    "keywords": [
        "lwc"
    ],
    "license": "MIT",
    "nodemonConfig": {
        "watch": [
            "src/server/**/*.js"
        ],
        "ext": "js",
        "ignore": [
            "src/**/*.spec.js",
            "src/**/*.test.js"
        ],
        "exec": "node ./src/server/api.js"
    },
    "repository": "Fellipe Demoraes/app",
    "scripts": {
        "build": "lwc-services build -m production",
        "build:development": "lwc-services build",
        "lint": "eslint ./src/**/*.js",
        "postinstall": "husky install",
        "precommit": "npm run prettier:verify && [ $? -eq 0 ] && npm run lint",
        "prettier": "prettier --write \"**/*.{css,html,js,json,md,ts,yaml,yml}\"",
        "prettier:verify": "prettier --list-different \"**/*.{css,html,js,json,md,ts,yaml,yml}\"",
        "start": "run-p start:client start:api",
        "start:api": "node src/server/api.js",
        "start:client": "node scripts/server.js",
        "test:unit": "lwc-services test:unit",
        "test:unit:coverage": "lwc-services test:unit --coverage",
        "test:unit:debug": "lwc-services test:unit --debug",
        "test:unit:watch": "lwc-services test:unit --watch",
        "watch": "run-p watch:client watch:server",
        "watch:client": "lwc-services watch",
        "watch:server": "nodemon"
    },
    "devDependencies": {
        "eslint": "^7.32.0",
        "eslint-plugin-inclusive-language": "^2.2.0",
        "husky": "^7.0.4",
        "lwc-services": "^3.2.2",
        "nodemon": "^2.0.15",
        "npm-run-all": "^4.1.5",
        "prettier": "^2.5.1"
    }
}
```
Also I may have had to install nodemon myself because i didn't see it in the devDependencies. 
I'm using lwc-services 3.2.2, node version 17.3.0, npm version 8.3.0.

**Comment by fddemora** [comment]
works fine on macos...
