### ISSUE TITLE
UnhandlesPromiseRejectionWarning when generating app

### ISSUE THREAD

**Issue by jhuizenga** [muenzpraeger/create-lwc-app#932]
### Summary

When generating with all defaults on (simple setup, name: my-app, standard web app, no express api server), it shows a UnhandlesPromiseRejectionWarning:

   create scripts/server.js
(node:41769) UnhandledPromiseRejectionWarning: TypeError: Object.entries(...).map(...).flat(...) is not a function or its return value is not iterable
    at Environment.getAllGenerators (/home/jacob/.npm/_npx/41769/lib/node_modules/create-lwc-app/node_modules/yeoman-environment/lib/environment.js:851:10)
    at Environment.getGeneratorsFeatures (/home/jacob/.npm/_npx/41769/lib/node_modules/create-lwc-app/node_modules/yeoman-environment/lib/generator-features.js:11:51)
    at Environment.getGeneratorsFeature (/home/jacob/.npm/_npx/41769/lib/node_modules/create-lwc-app/node_modules/yeoman-environment/lib/generator-features.js:24:12)
    at Environment.getGeneratorUniqueFunctionFeature (/home/jacob/.npm/_npx/41769/lib/node_modules/create-lwc-app/node_modules/yeoman-environment/lib/generator-features.js:38:48)
    at Environment.findGeneratorCustomCommitTask (/home/jacob/.npm/_npx/41769/lib/node_modules/create-lwc-app/node_modules/yeoman-environment/lib/generator-features.js:65:17)
    at runLoop.add (/home/jacob/.npm/_npx/41769/lib/node_modules/create-lwc-app/node_modules/yeoman-environment/lib/environment.js:1243:37)
    at Immediate.setImmediate (/home/jacob/.npm/_npx/41769/lib/node_modules/create-lwc-app/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:41769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:41769) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Additional information

Node version: v10.19.0
Npm/npx version: 6.14.4

**Comment by muenzpraeger** [comment]
Does the same error occur with node14? Node10 is very old.

Also please note that `create-lwc-app` will soon be deprecated. Please [checkout the documentation](https://lwc.dev/guide/install#via-rollup) for an alternative approach.

**Comment by jhuizenga** [comment]
Wow, you're fast Rene.. I hoped to be able to delete the issue before you read it.. guess that's too late now ;-) Found out about the Node version when investigating the issue, installed Node 14 and it generates without any problem now. Thnx for the tip about Rollup, will check it out!
